services:
  - type: web
    name: telegram-birthday-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromSecret: TELEGRAM_BOT_TOKEN
      - key: FIREBASE_DB_URL
        fromSecret: FIREBASE_DB_URL
      - key: FIREBASE_KEY_BASE64
        fromSecret: FIREBASE_KEY_BASE64
      - key: BOT_USERNAME
        fromSecret: BOT_USERNAME
      - key: TIMEZONE
        value: Europe/Moscow
